### ISSUE TITLE
Update eslint to v8

### ISSUE THREAD

**Issue by tomikawa-san** [freee/eslint-config-freee-typescript#13]
依存するeslintをv8にupdate可能でしょうか？
https://github.com/freee/eslint-config-freee-typescript/blob/master/package.json#L32

[最新のreact scrpitsがeslint v8に依存](https://github.com/facebook/create-react-app/blob/main/package.json#L30)しているので、create-react-appしたプロジェクトにeslint-config-freee-typescriptを`npm install`するとconflictが発生するため。

**Comment by takumi0h** [comment]
@tomikawa-san [v0.5.0](https://github.com/freee/eslint-config-freee-typescript/releases/tag/v0.5.0)で対応しました 🙏
